export const HANDLE_CART_PREVIEW = "HANDLE_CART_PREVIEW";
export const ADD_CART_MODAL = "ADD_CART_MODAL";

export const HANDLE_LOCK_BODY = "HANDLE_LOCK_BODY";

export const HANDLE_ORDER_MODAL = "HANDLE_ORDER_MODAL";

export const HANDLE_HAMBURGER_MENU = "HANDLE_HAMBURGER_MENU";

export const HANDLE_DARK_SCREEN = "HANDLE_DARK_SCREEN";
